name: Terraform Preprod

on:
  push:
    branches:
      - main
    paths:
      - "environments/preprod/**"
      - "modules/**"

  pull_request:
    branches:
      - main
    paths:
      - "environments/preprod/**"
      - "modules/**"

permissions:
  contents: read

env:
  TF_WORKING_DIR: environments/preprod

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:

      # 1. Download repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # 3. Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # 6. Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"