name: Terraform CI - Feature Branch

on:
  push:
    branches:
      - "feature/**"

permissions:
  contents: read

jobs:

  # ==========================================
  # JOB 1 - GITLEAKS
  # ==========================================
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # ==========================================
  # JOB 2 - TERRAFORM
  # ==========================================
  terraform:
    name: Terraform Init Fmt Validate Plan
    runs-on: ubuntu-latest

    # Terraform will run only after Gitleaks succeeds
    needs: gitleaks

    defaults:
      run:
        working-directory: environments/preprod

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"