name: Terraform CI - Feature Branch

on:
  push:
    branches:
      - "feature/**"

permissions:
  contents: read

jobs:
  terraform:
    name: Security Scan and Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Scan repository for secrets
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_CONFIG: environments/.gitleaks.toml

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Azure Login
      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      # 5. Set subscription
      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      # 6. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 7. Terraform Format
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 8. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 9. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"